# This file is auto generated by bash2pwsh.js

#!/bin/bash
## node bash2pwsh.js ./You-can-test-with-this-bash-script/test.bash  test.ps1

## Test
find terminal/git/ -name "*.git" -print0 | xargs -0 -I file mv file old_files/